Add job types student, add feature groups
tamashii-io/tamashii-clockin pull request #4
Opened 2019-03-26 10:50 UTC by jimmy2822

* 新增員工類別：學員
* 新增功能：群組
  可以為員工添加複數群組,可以為空白。

2019-03-27 10:09 UTC, elct9620 requested changes
然後 package-lock.json 是多的檔案要刪掉

2019-03-27 10:09 UTC, elct9620 commented on app/models/group_list.rb
> +class GroupList < ApplicationRecord
這個不是說想過一個適合一點的名字嗎 🤔

2019-03-27 10:09 UTC, elct9620 commented on app/assets/stylesheets/application.scss
> +.group-tool {
這應該去查版型能怎樣放吧，不是去調他外觀

2019-03-27 10:09 UTC, elct9620 commented on spec/models/check_record_spec.rb
> +    it { CheckRecord.reflect_on_association(:user).macro.should eq(:belongs_to) }
這邊要用 shoulda 的方法去寫，不是把他改掉

2019-03-28 04:11 UTC, elct9620 requested changes

2019-03-28 04:11 UTC, elct9620 commented on app/models/grouping.rb
> +class Grouping < ApplicationRecord
這叫 membership 都會比 grouping 好吧 :joy:

2019-03-28 04:11 UTC, elct9620 commented
測試還是壞的

2019-03-28 04:27 UTC, jimmy2822 commented
> 測試還是壞的

2019-03-28 06:12 UTC, elct9620 requested changes
package-lock.json 沒刪掉

2019-03-28 06:18 UTC, elct9620 approved these changes

2019-03-28 06:19 UTC, merged